swagger: '2.0'
info:
  title: Gym Management API
  description: API for retreave user information related to gym management
  version: v1
paths:
  /CreateAttence:
    post:
      tags:
        - Attendence
      summary: Create an attendence
      produces:
        - application/json
      parameters:
        - in: query
          name: AttendenceId
          type: integer
          format: int32
        - in: query
          name: UserId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: IsPresent
          type: boolean
        - in: query
          name: Date
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /UpdateAttendence:
    put:
      tags:
        - Attendence
      summary: Update an attendence
      produces:
        - application/json
      parameters:
        - in: query
          name: AttendenceId
          type: integer
          format: int32
        - in: query
          name: UserId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: IsPresent
          type: boolean
        - in: query
          name: Date
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllAttendenceByUser:
    get:
      tags:
        - Attendence
      summary: Get all attendence by an User
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Type
          type: integer
          format: int32
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: ExerciseId
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /Request:
    post:
      tags:
        - Authentication
      summary: Request a user authentication
      produces:
        - application/json
      parameters:
        - in: query
          name: Password
          type: string
        - in: query
          name: Name
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /CreateDiet:
    post:
      tags:
        - Diet
      summary: Create a new diet for a user
      produces:
        - application/json
      parameters:
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: Foods
          type: array
          items:
            $ref: '#/definitions/Food'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /UpdateDiet:
    put:
      tags:
        - Diet
      summary: Update and Diet
      produces:
        - application/json
      parameters:
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: Foods
          type: array
          items:
            $ref: '#/definitions/Food'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllDietsByUser:
    get:
      tags:
        - Diet
      summary: List all Diets for an User
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Type
          type: integer
          format: int32
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: ExerciseId
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllDietsByUserByMonth:
    get:
      tags:
        - Diet
      summary: List All Diets for a User for an specific month
      produces:
        - application/json
      parameters:
        - in: query
          name: id
          description: ''
          type: integer
          format: int32
        - in: query
          name: month
          description: ''
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /CreateExercise:
    post:
      tags:
        - Exercise
      summary: Create an Exercise
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Description
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllExerciseByUser:
    get:
      tags:
        - Exercise
      produces:
        - application/json
      parameters:
        - in: query
          name: userId
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /UpdateExerciseByUser:
    put:
      tags:
        - Exercise
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Description
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /CreateSchedule:
    post:
      tags:
        - Schedule
      summary: Create an Schedule
      produces:
        - application/json
      parameters:
        - in: query
          name: Date
          type: string
          format: date-time
        - in: query
          name: Name
          type: string
        - in: query
          name: TypeId
          type: integer
          format: int32
        - in: query
          name: Location
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /UpdateScheduleByUser:
    put:
      tags:
        - Schedule
      summary: update a schedule
      produces:
        - application/json
      parameters:
        - in: query
          name: Date
          type: string
          format: date-time
        - in: query
          name: Name
          type: string
        - in: query
          name: TypeId
          type: integer
          format: int32
        - in: query
          name: Location
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllScheduleByUser:
    get:
      tags:
        - Schedule
      summary: Get all Schedules for an User
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Type
          type: integer
          format: int32
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: ExerciseId
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /User/CreateUser:
    post:
      tags:
        - User
      summary: Create an User
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Success
          schema:
            format: int32
            type: integer
  /User/GetAllUsers:
    get:
      tags:
        - User
      summary: Return All Users
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /User/UpdateUser:
    post:
      tags:
        - User
      summary: Update an User
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /User/GetUserById:
    get:
      tags:
        - User
      summary: Get a User
      produces:
        - application/json
      parameters:
        - in: query
          name: Id
          description: ''
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /CreateWorkout:
    post:
      tags:
        - WorkOut
      summary: Create a new Workout
      produces:
        - application/json
      parameters:
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: Exercise.Name
          type: string
        - in: query
          name: Exercise.Description
          type: string
        - in: query
          name: Date
          type: string
          format: date-time
        - in: query
          name: Time.Hour
          type: integer
          format: int32
        - in: query
          name: Time.Minute
          type: integer
          format: int32
        - in: query
          name: Time.Second
          type: integer
          format: int32
        - in: query
          name: Time.Millisecond
          type: integer
          format: int32
        - in: query
          name: Time.Ticks
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /UpdateWorkout:
    put:
      tags:
        - WorkOut
      summary: Update a Workout
      produces:
        - application/json
      parameters:
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: Exercise.Name
          type: string
        - in: query
          name: Exercise.Description
          type: string
        - in: query
          name: Date
          type: string
          format: date-time
        - in: query
          name: Time.Hour
          type: integer
          format: int32
        - in: query
          name: Time.Minute
          type: integer
          format: int32
        - in: query
          name: Time.Second
          type: integer
          format: int32
        - in: query
          name: Time.Millisecond
          type: integer
          format: int32
        - in: query
          name: Time.Ticks
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
  /GetAllWorkoutByUser:
    get:
      tags:
        - WorkOut
      summary: Get All Workouts for an User
      produces:
        - application/json
      parameters:
        - in: query
          name: Name
          type: string
        - in: query
          name: Type
          type: integer
          format: int32
        - in: query
          name: DietId
          type: integer
          format: int32
        - in: query
          name: ScheduleId
          type: integer
          format: int32
        - in: query
          name: WorkoutId
          type: integer
          format: int32
        - in: query
          name: ExerciseId
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/HttpResponseMessage'
definitions:
  Food:
    type: object
    properties:
      name:
        type: string
      quantityLbs:
        format: double
        type: number
  HttpContent:
    type: object
    properties:
      headers:
        type: array
        items:
          $ref: '#/definitions/StringStringIEnumerableKeyValuePair'
        readOnly: true
  HttpMethod:
    type: object
    properties:
      method:
        type: string
  HttpRequestMessage:
    type: object
    properties:
      version:
        $ref: '#/definitions/Version'
      versionPolicy:
        $ref: '#/definitions/HttpVersionPolicy'
      content:
        $ref: '#/definitions/HttpContent'
      method:
        $ref: '#/definitions/HttpMethod'
      requestUri:
        format: uri
        type: string
      headers:
        type: array
        items:
          $ref: '#/definitions/StringStringIEnumerableKeyValuePair'
        readOnly: true
      properties:
        type: object
        additionalProperties: { }
        readOnly: true
      options:
        type: object
        additionalProperties: { }
        readOnly: true
  HttpResponseMessage:
    type: object
    properties:
      version:
        $ref: '#/definitions/Version'
      content:
        $ref: '#/definitions/HttpContent'
      statusCode:
        $ref: '#/definitions/HttpStatusCode'
      reasonPhrase:
        type: string
      headers:
        type: array
        items:
          $ref: '#/definitions/StringStringIEnumerableKeyValuePair'
        readOnly: true
      trailingHeaders:
        type: array
        items:
          $ref: '#/definitions/StringStringIEnumerableKeyValuePair'
        readOnly: true
      requestMessage:
        $ref: '#/definitions/HttpRequestMessage'
      isSuccessStatusCode:
        type: boolean
        readOnly: true
  HttpStatusCode:
    format: int32
    enum:
      - 100
      - 101
      - 102
      - 103
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 400
      - 401
      - 402
      - 403
      - 404
      - 405
      - 406
      - 407
      - 408
      - 409
      - 410
      - 411
      - 412
      - 413
      - 414
      - 415
      - 416
      - 417
      - 421
      - 422
      - 423
      - 424
      - 426
      - 428
      - 429
      - 431
      - 451
      - 500
      - 501
      - 502
      - 503
      - 504
      - 505
      - 506
      - 507
      - 508
      - 510
      - 511
    type: integer
  HttpVersionPolicy:
    format: int32
    enum:
      - 0
      - 1
      - 2
    type: integer
  StringStringIEnumerableKeyValuePair:
    type: object
    properties:
      key:
        type: string
      value:
        type: array
        items:
          type: string
  User:
    type: object
    properties:
      name:
        type: string
      type:
        format: int32
        type: integer
      dietId:
        format: int32
        type: integer
      scheduleId:
        format: int32
        type: integer
      workoutId:
        format: int32
        type: integer
      exerciseId:
        format: int32
        type: integer
  Version:
    type: object
    properties:
      major:
        format: int32
        type: integer
      minor:
        format: int32
        type: integer
      build:
        format: int32
        type: integer
      revision:
        format: int32
        type: integer
      majorRevision:
        format: int32
        type: integer
        readOnly: true
      minorRevision:
        format: int32
        type: integer
        readOnly: true
